# Generated by Django 2.2.4 on 2019-08-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_courtbooking_lessonbooking_tenniscomplex_tennislessonbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfLessonBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('pro', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_lesson_bookings', to='scheduler_app.GolfCourse')),
            ],
        ),
        migrations.DeleteModel(
            name='LessonBooking',
        ),
    ]
